version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: shopee_postgres
    environment:
      POSTGRES_DB: shopee_patrol
      POSTGRES_USER: shopee_user
      POSTGRES_PASSWORD: shopee123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: