#!/bin/bash

echo "🚀 Chạy hệ thống đơn giản với ngrok"
echo "=================================="

# Bước 1: Khởi động ngrok
echo "1️⃣ Khởi động ngrok..."
ngrok http 8000 --log=stdout > ngrok.log 2>&1 &
NGROK_PID=$!

echo "⏳ Đợi ngrok khởi động..."
sleep 5

# Bước 2: Lấy ngrok URL
echo "2️⃣ Lấy ngrok URL..."
NGROK_URL=""
for i in {1..10}; do
    NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    for tunnel in data.get('tunnels', []):
        if tunnel.get('proto') == 'https':
            print(tunnel.get('public_url'))
            break
except:
    pass
" 2>/dev/null)
    
    if [ ! -z "$NGROK_URL" ]; then
        break
    fi
    echo "⏳ Đợi ngrok URL... ($i/10)"
    sleep 2
done

if [ -z "$NGROK_URL" ]; then
    echo "❌ Không thể lấy ngrok URL"
    kill $NGROK_PID 2>/dev/null
    exit 1
fi

echo "✅ Ngrok URL: $NGROK_URL"

# Bước 3: Cập nhật .env
echo "3️⃣ Cập nhật file .env..."
cat > .env << EOF
# Auto-generated by run-simple.sh
NGROK_URL=$NGROK_URL
VITE_API_URL=$NGROK_URL

# Other environment variables
# VITE_API_BASE_URL=https://10.10.68.200:8000/api
# VITE_API_BASE_URL=https://localhost:8000/api
EOF

echo "✅ Đã cập nhật .env với URL: $NGROK_URL"

# Bước 4: Khởi động backend
echo "4️⃣ Khởi động backend..."
cd backend
python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload &
BACKEND_PID=$!
cd ..

echo "⏳ Đợi backend khởi động..."
sleep 3

# Bước 5: Khởi động frontend
echo "5️⃣ Khởi động frontend..."
cd frontend
npm run dev &
FRONTEND_PID=$!
cd ..

echo ""
echo "🎉 Hệ thống đã khởi động!"
echo "🌐 Ngrok URL: $NGROK_URL"
echo "📱 Truy cập từ điện thoại: $NGROK_URL"
echo ""
echo "💡 Để dừng hệ thống, nhấn Ctrl+C"

# Function để cleanup khi dừng
cleanup() {
    echo ""
    echo "🛑 Đang dừng hệ thống..."
    kill $NGROK_PID 2>/dev/null
    kill $BACKEND_PID 2>/dev/null
    kill $FRONTEND_PID 2>/dev/null
    echo "✅ Đã dừng hệ thống"
    exit 0
}

# Trap Ctrl+C
trap cleanup SIGINT

# Giữ script chạy
wait

