#!/bin/bash

echo "🌍 Khởi động hệ thống với Cloudflare Tunnel"
echo "==========================================="

# Dừng các process cũ
echo "🛑 Dừng các process cũ..."
pkill -f "uvicorn.*app.main:app" 2>/dev/null
pkill -f "npm run dev" 2>/dev/null
pkill -f "vite" 2>/dev/null
pkill -f "cloudflared" 2>/dev/null
pkill -f "ngrok" 2>/dev/null
sleep 2

# Khởi động backend
echo "🐍 Khởi động backend..."
cd backend
python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload &
BACKEND_PID=$!
cd ..

echo "⏳ Đợi backend khởi động..."
sleep 3

# Khởi động frontend
echo "🌐 Khởi động frontend..."
cd frontend
npm run dev -- --host 0.0.0.0 --port 5173 &
FRONTEND_PID=$!
cd ..

echo "⏳ Đợi frontend khởi động..."
sleep 5

# Khởi động Cloudflare tunnel cho backend
echo "🚀 Khởi động Cloudflare tunnel cho backend..."
cloudflared tunnel --url http://localhost:8000 > cloudflare-backend.log 2>&1 &
CLOUDFLARE_BACKEND_PID=$!

echo "⏳ Đợi Cloudflare backend tunnel khởi động..."
sleep 3

# Khởi động Cloudflare tunnel cho frontend
echo "🚀 Khởi động Cloudflare tunnel cho frontend..."
cloudflared tunnel --url https://localhost:5173 > cloudflare-frontend.log 2>&1 &
CLOUDFLARE_FRONTEND_PID=$!

echo "⏳ Đợi Cloudflare frontend tunnel khởi động..."
sleep 3

# Lấy URLs từ log files
echo "🔍 Lấy Cloudflare URLs..."

# Đợi một chút để URLs được tạo
sleep 5

# Lấy backend URL
BACKEND_URL=""
if [ -f "cloudflare-backend.log" ]; then
    BACKEND_URL=$(grep -o 'https://[^[:space:]]*\.trycloudflare\.com' cloudflare-backend.log | head -1)
fi

# Lấy frontend URL  
FRONTEND_URL=""
if [ -f "cloudflare-frontend.log" ]; then
    FRONTEND_URL=$(grep -o 'https://[^[:space:]]*\.trycloudflare\.com' cloudflare-frontend.log | head -1)
fi

echo ""
echo "🎉 HỆ THỐNG ĐÃ SẴN SÀNG VỚI CLOUDFLARE!"
echo "======================================="

if [ ! -z "$BACKEND_URL" ]; then
    echo "🌐 Backend URL: $BACKEND_URL"
else
    echo "🌐 Backend URL: Đang khởi động... (kiểm tra cloudflare-backend.log)"
fi

if [ ! -z "$FRONTEND_URL" ]; then
    echo "🌐 Frontend URL: $FRONTEND_URL"
    echo ""
    echo "📱 TRUY CẬP TỪ BẤT KỲ ĐÂU:"
    echo "   $FRONTEND_URL"
    
    # Cập nhật .env với frontend URL
    echo "📝 Cập nhật file .env với Cloudflare URL..."
    cat > frontend/.env << EOF
# Auto-generated by start-cloudflare.sh
CLOUDFLARE_FRONTEND_URL=$FRONTEND_URL
VITE_API_URL=$FRONTEND_URL
VITE_API_BASE_URL=$FRONTEND_URL/api
VITE_FRONTEND_URL=$FRONTEND_URL
VITE_BACKEND_URL=$FRONTEND_URL
VITE_WS_URL=$FRONTEND_URL/ws
EOF
    
    echo "✅ Đã cập nhật .env với Cloudflare URL"
else
    echo "🌐 Frontend URL: Đang khởi động... (kiểm tra cloudflare-frontend.log)"
fi

echo ""
echo "✅ Tất cả API calls và ảnh đều sử dụng Cloudflare URL"
echo "✅ Có thể truy cập từ 4G, WiFi khác, mạng khác"
echo "✅ Đăng nhập, face auth, upload ảnh đều hoạt động"
echo "✅ Miễn phí hoàn toàn, không giới hạn bandwidth"
echo ""
echo "📋 Log files:"
echo "   Backend: cloudflare-backend.log"
echo "   Frontend: cloudflare-frontend.log"
echo ""
echo "💡 Để dừng hệ thống, nhấn Ctrl+C"

# Function để cleanup khi dừng
cleanup() {
    echo ""
    echo "🛑 Đang dừng hệ thống..."
    kill $BACKEND_PID 2>/dev/null
    kill $FRONTEND_PID 2>/dev/null
    kill $CLOUDFLARE_BACKEND_PID 2>/dev/null
    kill $CLOUDFLARE_FRONTEND_PID 2>/dev/null
    pkill -f "uvicorn.*app.main:app" 2>/dev/null
    pkill -f "npm run dev" 2>/dev/null
    pkill -f "vite" 2>/dev/null
    pkill -f "cloudflared" 2>/dev/null
    echo "✅ Đã dừng hệ thống"
    exit 0
}

# Trap Ctrl+C
trap cleanup SIGINT

# Giữ script chạy và hiển thị URLs khi có
while true; do
    sleep 10
    
    # Kiểm tra lại URLs
    if [ -f "cloudflare-backend.log" ]; then
        NEW_BACKEND_URL=$(grep -o 'https://[^[:space:]]*\.trycloudflare\.com' cloudflare-backend.log | head -1)
        if [ ! -z "$NEW_BACKEND_URL" ] && [ "$NEW_BACKEND_URL" != "$BACKEND_URL" ]; then
            BACKEND_URL="$NEW_BACKEND_URL"
            echo "🔄 Backend URL: $BACKEND_URL"
        fi
    fi
    
    if [ -f "cloudflare-frontend.log" ]; then
        NEW_FRONTEND_URL=$(grep -o 'https://[^[:space:]]*\.trycloudflare\.com' cloudflare-frontend.log | head -1)
        if [ ! -z "$NEW_FRONTEND_URL" ] && [ "$NEW_FRONTEND_URL" != "$FRONTEND_URL" ]; then
            FRONTEND_URL="$NEW_FRONTEND_URL"
            echo "🔄 Frontend URL: $FRONTEND_URL"
            echo "📱 TRUY CẬP: $FRONTEND_URL"
            
            # Cập nhật .env
            cat > frontend/.env << EOF
# Auto-generated by start-cloudflare.sh
CLOUDFLARE_FRONTEND_URL=$FRONTEND_URL
VITE_API_URL=$FRONTEND_URL
VITE_API_BASE_URL=$FRONTEND_URL/api
VITE_FRONTEND_URL=$FRONTEND_URL
VITE_BACKEND_URL=$FRONTEND_URL
VITE_WS_URL=$FRONTEND_URL/ws
EOF
        fi
    fi
done
