#!/bin/bash

echo "🚀 Khởi động hệ thống hoàn chỉnh với ngrok"
echo "=========================================="

# Dừng các process cũ
echo "🛑 Dừng các process cũ..."
pkill -f "uvicorn.*app.main:app" 2>/dev/null
pkill -f "npm run dev" 2>/dev/null
pkill -f "vite" 2>/dev/null
pkill -f "ngrok" 2>/dev/null
sleep 2

# Khởi động backend
echo "🐍 Khởi động backend..."
cd backend
python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload &
BACKEND_PID=$!
cd ..

echo "⏳ Đợi backend khởi động..."
sleep 3

# Khởi động frontend
echo "🌐 Khởi động frontend..."
cd frontend
npm run dev -- --host 0.0.0.0 --port 5173 &
FRONTEND_PID=$!
cd ..

echo "⏳ Đợi frontend khởi động..."
sleep 5

# Khởi động ngrok cho backend
echo "🚀 Khởi động ngrok cho backend..."
ngrok http 0.0.0.0:8000 --log=stdout > ngrok-backend.log 2>&1 &
NGROK_BACKEND_PID=$!

echo "⏳ Đợi ngrok backend khởi động..."
sleep 5

# Lấy ngrok URL cho backend
echo "🔍 Lấy ngrok URL cho backend..."
NGROK_BACKEND_URL=""
for i in {1..10}; do
    NGROK_BACKEND_URL=$(curl -s http://localhost:4040/api/tunnels | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    for tunnel in data.get('tunnels', []):
        if tunnel.get('proto') == 'https':
            print(tunnel.get('public_url'))
            break
except:
    pass
" 2>/dev/null)
    
    if [ ! -z "$NGROK_BACKEND_URL" ]; then
        break
    fi
    echo "⏳ Đợi ngrok backend URL... ($i/10)"
    sleep 2
done

if [ -z "$NGROK_BACKEND_URL" ]; then
    echo "❌ Không thể lấy ngrok backend URL"
    kill $BACKEND_PID 2>/dev/null
    kill $FRONTEND_PID 2>/dev/null
    kill $NGROK_BACKEND_PID 2>/dev/null
    exit 1
fi

echo "✅ Ngrok Backend URL: $NGROK_BACKEND_URL"

# Cập nhật .env
echo "📝 Cập nhật file .env..."
cat > .env << EOF
# Auto-generated by start-complete.sh
NGROK_URL=$NGROK_BACKEND_URL
VITE_API_URL=$NGROK_BACKEND_URL

# Other environment variables
# VITE_API_BASE_URL=https://10.10.68.200:8000/api
# VITE_API_BASE_URL=https://localhost:8000/api
EOF

echo "✅ Đã cập nhật .env với URL: $NGROK_BACKEND_URL"

# Restart frontend để đọc .env mới
echo "🔄 Restart frontend với cấu hình mới..."
kill $FRONTEND_PID 2>/dev/null
sleep 2

cd frontend
npm run dev -- --host 0.0.0.0 --port 5173 &
FRONTEND_PID=$!
cd ..

echo "⏳ Đợi frontend restart..."
sleep 5

# Khởi động ngrok cho frontend
echo "🚀 Khởi động ngrok cho frontend..."
ngrok http https://10.10.68.200:5173 --log=stdout > ngrok-frontend.log 2>&1 &
NGROK_FRONTEND_PID=$!

echo "⏳ Đợi ngrok frontend khởi động..."
sleep 5

# Lấy ngrok URL cho frontend
echo "🔍 Lấy ngrok URL cho frontend..."
NGROK_FRONTEND_URL=""
for i in {1..10}; do
    NGROK_FRONTEND_URL=$(curl -s http://localhost:4041/api/tunnels | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    for tunnel in data.get('tunnels', []):
        if tunnel.get('proto') == 'https':
            print(tunnel.get('public_url'))
            break
except:
    pass
" 2>/dev/null)
    
    if [ ! -z "$NGROK_FRONTEND_URL" ]; then
        break
    fi
    echo "⏳ Đợi ngrok frontend URL... ($i/10)"
    sleep 2
done

echo ""
echo "🎉 Hệ thống đã khởi động hoàn chỉnh!"
echo "🌐 Backend URL: $NGROK_BACKEND_URL"
if [ ! -z "$NGROK_FRONTEND_URL" ]; then
    echo "🌐 Frontend URL: $NGROK_FRONTEND_URL"
else
    echo "🌐 Frontend URL: https://10.10.68.200:5173 (local)"
fi
echo ""
echo "📱 Truy cập từ điện thoại:"
if [ ! -z "$NGROK_FRONTEND_URL" ]; then
    echo "   $NGROK_FRONTEND_URL"
else
    echo "   https://10.10.68.200:5173"
fi
echo ""
echo "🔗 Ngrok Dashboard:"
echo "   Backend: http://localhost:4040"
if [ ! -z "$NGROK_FRONTEND_URL" ]; then
    echo "   Frontend: http://localhost:4041"
fi
echo ""
echo "💡 Để dừng hệ thống, nhấn Ctrl+C"

# Function để cleanup khi dừng
cleanup() {
    echo ""
    echo "🛑 Đang dừng hệ thống..."
    kill $BACKEND_PID 2>/dev/null
    kill $FRONTEND_PID 2>/dev/null
    kill $NGROK_BACKEND_PID 2>/dev/null
    kill $NGROK_FRONTEND_PID 2>/dev/null
    pkill -f "uvicorn.*app.main:app" 2>/dev/null
    pkill -f "npm run dev" 2>/dev/null
    pkill -f "vite" 2>/dev/null
    pkill -f "ngrok" 2>/dev/null
    echo "✅ Đã dừng hệ thống"
    exit 0
}

# Trap Ctrl+C
trap cleanup SIGINT

# Giữ script chạy
wait
