#!/bin/bash

echo "🌐 Khởi động hệ thống với ngrok HTTPS"
echo "===================================="

# Kiểm tra ngrok đã cấu hình chưa
if ! ngrok config check &> /dev/null; then
    echo "❌ Ngrok chưa được cấu hình!"
    echo "💡 Chạy: ./setup-ngrok-token.sh"
    exit 1
fi

# Dừng các process cũ
echo "🛑 Dừng các process cũ..."
pkill -f "uvicorn.*app.main:app" 2>/dev/null
pkill -f "npm run dev" 2>/dev/null
pkill -f "vite" 2>/dev/null
pkill -f "ngrok" 2>/dev/null
sleep 2

# Khởi động ngrok
echo "🚀 Khởi động ngrok..."
ngrok http 8000 --log=stdout > ngrok.log 2>&1 &
NGROK_PID=$!

echo "⏳ Đợi ngrok khởi động..."
sleep 5

# Lấy ngrok URL
echo "🔍 Lấy ngrok URL..."
NGROK_URL=""
for i in {1..15}; do
    NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    for tunnel in data.get('tunnels', []):
        if tunnel.get('proto') == 'https':
            print(tunnel.get('public_url'))
            break
except:
    pass
" 2>/dev/null)
    
    if [ ! -z "$NGROK_URL" ]; then
        break
    fi
    echo "⏳ Đợi ngrok URL... ($i/15)"
    sleep 2
done

if [ -z "$NGROK_URL" ]; then
    echo "❌ Không thể lấy ngrok URL"
    kill $NGROK_PID 2>/dev/null
    exit 1
fi

echo "✅ Ngrok HTTPS URL: $NGROK_URL"

# Cập nhật .env
echo "📝 Cập nhật file .env..."
cat > .env << EOF
# Auto-generated by start-with-ngrok-https.sh
NGROK_URL=$NGROK_URL
VITE_API_URL=$NGROK_URL

# Other environment variables
# VITE_API_BASE_URL=https://10.10.68.200:8000/api
# VITE_API_BASE_URL=https://localhost:8000/api
EOF

echo "✅ Đã cập nhật .env với URL: $NGROK_URL"

# Khởi động backend
echo "🐍 Khởi động backend..."
cd backend
python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload &
BACKEND_PID=$!
cd ..

echo "⏳ Đợi backend khởi động..."
sleep 3

# Khởi động frontend
echo "🌐 Khởi động frontend..."
cd frontend
npm run dev &
FRONTEND_PID=$!
cd ..

echo "⏳ Đợi frontend khởi động..."
sleep 5

echo ""
echo "🎉 Hệ thống đã khởi động với ngrok HTTPS!"
echo "🌐 HTTPS URL: $NGROK_URL"
echo "📱 Truy cập từ điện thoại: $NGROK_URL"
echo "💻 Truy cập từ máy tính: $NGROK_URL"
echo ""
echo "🔗 Ngrok Dashboard: http://localhost:4040"
echo "💡 Để dừng hệ thống, nhấn Ctrl+C"

# Function để cleanup khi dừng
cleanup() {
    echo ""
    echo "🛑 Đang dừng hệ thống..."
    kill $NGROK_PID 2>/dev/null
    kill $BACKEND_PID 2>/dev/null
    kill $FRONTEND_PID 2>/dev/null
    pkill -f "uvicorn.*app.main:app" 2>/dev/null
    pkill -f "npm run dev" 2>/dev/null
    pkill -f "vite" 2>/dev/null
    pkill -f "ngrok" 2>/dev/null
    echo "✅ Đã dừng hệ thống"
    exit 0
}

# Trap Ctrl+C
trap cleanup SIGINT

# Giữ script chạy
wait

