#!/bin/bash

echo "🌍 Khởi động hệ thống toàn cầu (truy cập từ mọi mạng)"
echo "=================================================="

# Dừng các process cũ
echo "🛑 Dừng các process cũ..."
pkill -f "uvicorn.*app.main:app" 2>/dev/null
pkill -f "npm run dev" 2>/dev/null
pkill -f "vite" 2>/dev/null
pkill -f "ngrok" 2>/dev/null
sleep 2

# Khởi động backend
echo "🐍 Khởi động backend..."
cd backend
python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload &
BACKEND_PID=$!
cd ..

echo "⏳ Đợi backend khởi động..."
sleep 3

# Khởi động ngrok cho backend
echo "🚀 Khởi động ngrok cho backend..."
ngrok http 0.0.0.0:8000 --log=stdout > ngrok-backend.log 2>&1 &
NGROK_BACKEND_PID=$!

echo "⏳ Đợi ngrok backend khởi động..."
sleep 5

# Lấy ngrok URL cho backend
echo "🔍 Lấy ngrok URL cho backend..."
BACKEND_NGROK_URL=""
for i in {1..10}; do
    BACKEND_NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    for tunnel in data.get('tunnels', []):
        if tunnel.get('proto') == 'https':
            print(tunnel.get('public_url'))
            break
except:
    pass
" 2>/dev/null)
    
    if [ ! -z "$BACKEND_NGROK_URL" ]; then
        break
    fi
    echo "⏳ Đợi backend ngrok URL... ($i/10)"
    sleep 2
done

if [ -z "$BACKEND_NGROK_URL" ]; then
    echo "❌ Không thể lấy backend ngrok URL"
    kill $BACKEND_PID 2>/dev/null
    kill $NGROK_BACKEND_PID 2>/dev/null
    exit 1
fi

echo "✅ Backend Ngrok URL: $BACKEND_NGROK_URL"

# Cập nhật .env với backend URL
echo "📝 Cập nhật file .env với backend URL..."
cat > .env << EOF
# Auto-generated by start-global.sh
NGROK_URL=$BACKEND_NGROK_URL
VITE_API_URL=$BACKEND_NGROK_URL

# Other environment variables
# VITE_API_BASE_URL=https://10.10.68.200:8000/api
# VITE_API_BASE_URL=https://localhost:8000/api
EOF

# Khởi động frontend
echo "🌐 Khởi động frontend..."
cd frontend
npm run dev -- --host 0.0.0.0 --port 5173 &
FRONTEND_PID=$!
cd ..

echo "⏳ Đợi frontend khởi động..."
sleep 5

# Khởi động ngrok cho frontend (port 4041)
echo "🚀 Khởi động ngrok cho frontend..."
ngrok http https://10.10.68.200:5173 --log=stdout > ngrok-frontend.log 2>&1 &
NGROK_FRONTEND_PID=$!

echo "⏳ Đợi ngrok frontend khởi động..."
sleep 5

# Lấy ngrok URL cho frontend
echo "🔍 Lấy ngrok URL cho frontend..."
FRONTEND_NGROK_URL=""
for i in {1..10}; do
    FRONTEND_NGROK_URL=$(curl -s http://localhost:4041/api/tunnels | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    for tunnel in data.get('tunnels', []):
        if tunnel.get('proto') == 'https':
            print(tunnel.get('public_url'))
            break
except:
    pass
" 2>/dev/null)
    
    if [ ! -z "$FRONTEND_NGROK_URL" ]; then
        break
    fi
    echo "⏳ Đợi frontend ngrok URL... ($i/10)"
    sleep 2
done

if [ -z "$FRONTEND_NGROK_URL" ]; then
    echo "❌ Không thể lấy frontend ngrok URL"
    kill $BACKEND_PID 2>/dev/null
    kill $FRONTEND_PID 2>/dev/null
    kill $NGROK_BACKEND_PID 2>/dev/null
    kill $NGROK_FRONTEND_PID 2>/dev/null
    exit 1
fi

echo "✅ Frontend Ngrok URL: $FRONTEND_NGROK_URL"

echo ""
echo "🎉 Hệ thống đã khởi động toàn cầu!"
echo "🌐 Backend URL: $BACKEND_NGROK_URL"
echo "🌐 Frontend URL: $FRONTEND_NGROK_URL"
echo ""
echo "📱 Truy cập từ BẤT KỲ ĐÂU (mạng khác, 4G, WiFi khác):"
echo "   $FRONTEND_NGROK_URL"
echo ""
echo "🔗 Ngrok Dashboard:"
echo "   Backend: http://localhost:4040"
echo "   Frontend: http://localhost:4041"
echo "💡 Để dừng hệ thống, nhấn Ctrl+C"

# Function để cleanup khi dừng
cleanup() {
    echo ""
    echo "🛑 Đang dừng hệ thống..."
    kill $BACKEND_PID 2>/dev/null
    kill $FRONTEND_PID 2>/dev/null
    kill $NGROK_BACKEND_PID 2>/dev/null
    kill $NGROK_FRONTEND_PID 2>/dev/null
    pkill -f "uvicorn.*app.main:app" 2>/dev/null
    pkill -f "npm run dev" 2>/dev/null
    pkill -f "vite" 2>/dev/null
    pkill -f "ngrok" 2>/dev/null
    echo "✅ Đã dừng hệ thống"
    exit 0
}

# Trap Ctrl+C
trap cleanup SIGINT

# Giữ script chạy
wait
